[webservers]
web-server ansible_host=192.168.20.20

[databases]
db-server ansible_host=192.168.20.10

[soc]
soc-server ansible_host=192.168.30.10

[supervision]
soc-server ansible_host=192.168.30.10

[ia]
ia-server ansible_host=192.168.20.30

[runners]
runner-server ansible_host=192.168.50.10

[all:vars]
ansible_python_interpreter=/usr/bin/python3
