name: Deploy - Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'ansible/**'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  terraform:
    name: Terraform Plan
    runs-on: self-hosted

    env:
      TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
      TF_VAR_proxmox_token_id: ${{ secrets.PROXMOX_TOKEN_ID }}
      TF_VAR_proxmox_token_secret: ${{ secrets.PROXMOX_TOKEN_SECRET }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform plan
        working-directory: terraform
        run: terraform plan -parallelism=1

  ansible:
    name: Ansible Deploy
    runs-on: self-hosted
    needs: terraform

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ping toutes les VM
        working-directory: ansible
        run: ansible all -m ping

      - name: Common - configuration de base
        working-directory: ansible
        run: ansible-playbook playbooks/common.yml --forks=1

      - name: Base de donnees - PostgreSQL
        working-directory: ansible
        run: ansible-playbook playbooks/db.yml --forks=1

      - name: Application web - Nginx + Flask
        working-directory: ansible
        run: ansible-playbook playbooks/web.yml --forks=1

      - name: Supervision - Prometheus + Grafana + Loki
        working-directory: ansible
        run: ansible-playbook playbooks/supervision.yml --forks=1

      - name: SOC - Wazuh
        working-directory: ansible
        run: ansible-playbook playbooks/soc.yml --forks=1

      - name: IA - Isolation Forest
        working-directory: ansible
        run: ansible-playbook playbooks/ia.yml --forks=1

      - name: Runner - GitHub Actions
        working-directory: ansible
        run: ansible-playbook playbooks/runner.yml --forks=1
